AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-discord-bot
  A Serverless Discord Bot template built with Discord Slash Commands and AWS SAM.

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 3

Resources:
  DiscordDaoCommandsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./src/commands_layer

  DiscordDaoCreateCommandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/create_commands
      Description: "Function to create Discord Slash Commands"
      Handler: index.lambdaHandler
      Environment:
        Variables:
          DISCORD_APP_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:app_id}}'
          DISCORD_PUBLIC_KEY: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:public_key}}'
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          JWT_SECRET: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:jwt_secret}}'
      Layers:
        - !Ref DiscordDaoCommandsLayer

  DiscordDaoCreateCommandsInvoker:
    Type: Custom::DiscordDaoCreateCommandsInvoker
    Properties:
      ServiceToken: !GetAtt DiscordDaoCreateCommandsFunction.Arn
      # Passing the DiscordDaoCommandsLayer ARN will cause a custom resource update every time the commands are updated.
      # (note that the ARN of a LayerVersion Resource ends with an incrementing layer version number)
      DiscordDaoCommandsLayerVersion: !Ref DiscordDaoCommandsLayer

  DiscordDaoInteractionApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev

  DiscordDaoHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Description: "Serverless Function to handle incoming Discord requests"
      Handler: index.lambdaHandler
      Events:
        EthAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscordDaoInteractionApi
            Method: post
            Path: /event
      Environment:
        Variables:
          DISCORD_APP_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:app_id}}'
          DISCORD_PUBLIC_KEY: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:public_key}}'
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          JWT_SECRET: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:jwt_secret}}'
      Layers:
        - !Ref DiscordDaoCommandsLayer

  DiscordDaoRoleAssignFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: discord-dao-role-assign
      CodeUri: ./src/role_assignment
      Description: "Serverless Function to set the role of a given user on Discord"
      Handler: index.lambdaHandler
      Environment:
        Variables:
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          DISCORD_CHANNEL_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:channel_id}}'
          DISCORD_MANAGER_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:manager_role_id}}'
          DISCORD_INVESTOR_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:investor_role_id}}'

Outputs:
  DiscordDaoInteractionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DiscordDaoInteractionApi}.execute-api.${AWS::Region}.amazonaws.com/dev/event"
  DiscordRoleAssignFnArn:
    Description: "The ARN of the lambda function that assigns the roles on discord. Used to call that function after successful authentication."
    Value: !GetAtt DiscordDaoRoleAssignFunction.Arn
    Export:
      Name: DiscordDaoRoleAssignFnArn
