AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-discord-bot
  A Serverless Discord Bot template built with Discord Slash Commands and AWS SAM.

Globals:
  Function:
    Runtime: nodejs14.x
    # Must return response for slash commands in 3 secs, but after the response
    # the lambda can keep running to do stuff that's missing
    Timeout: 15

Resources:
  #EventBridgeBus:
  #  Type: AWS::Events::EventBus
  #  Properties:
  #    Name: discord-bus

  CommandsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./src/commands_layer

  CreateCommandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/create_commands
      Description: "Function to create Discord Slash Commands"
      Handler: index.lambdaHandler
      #Policies: 
      #  - LambdaInvokePolicy:
      #      FunctionName:
      #        !Ref DiscordPollResultsFunction
      Environment:
        Variables:
          DISCORD_APP_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:app_id}}'
          DISCORD_PUBLIC_KEY: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:public_key}}'
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          DISCORD_OWNER_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:owner_role_id}}'
          DISCORD_INVESTOR_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:investor_role_id}}'
          JWT_SECRET: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:jwt_secret}}'
          VAULT_ADDRESS: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:vault_address}}'
          ENZYME_API_ENDPOINT: !ImportValue 'EnzymeInteractionApi'
          DISCORD_POLL_RESULTS_FUNCTION: !Ref DiscordPollResultsFunction
      Layers:
        - !Ref CommandsLayer

  CreateCommandsInvoker:
    Type: Custom::CreateCommandsInvoker
    Properties:
      ServiceToken: !GetAtt CreateCommandsFunction.Arn
      # Passing the CommandsLayer ARN will cause a custom resource update every time the commands are updated.
      # (note that the ARN of a LayerVersion Resource ends with an incrementing layer version number)
      CommandsLayerVersion: !Ref CommandsLayer

  DiscordInteractionApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev

  DiscordHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/command_handler
      Description: "Serverless Function to handle incoming Discord requests"
      Handler: index.lambdaHandler
      Policies:
      - Statement:
        - Sid: EventBridgePutRulePolicy
          Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
          Resource: 
            #- !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/default"
            # Didn't check if it's possible to use regex for resource names in policies. 
            # If it is, would be best to allow only the rules with names started with `poll-results-rule-` 
            # (the rest of the name is a dynamic id based on timestamp)
            - !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/*"
        - Sid: LambdaAddPermissionPolicy
          Effect: Allow
          Action:
            - lambda:AddPermission
          Resource:
            - !GetAtt DiscordPollResultsFunction.Arn
      Events:
        EthAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref DiscordInteractionApi
            Method: post
            Path: /event
      Environment:
        Variables:
          DISCORD_APP_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:app_id}}'
          DISCORD_PUBLIC_KEY: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:public_key}}'
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          DISCORD_OWNER_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:owner_role_id}}'
          DISCORD_INVESTOR_ROLE_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:investor_role_id}}'
          JWT_SECRET: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:jwt_secret}}'
          VAULT_ADDRESS: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:vault_address}}'
          ENZYME_API_ENDPOINT: !ImportValue 'EnzymeInteractionApi'
          DISCORD_POLL_RESULTS_FUNCTION_ARN: !GetAtt DiscordPollResultsFunction.Arn
          #EVENT_BUS_NAME: !Ref EventBridgeBus
      Layers:
        - !Ref CommandsLayer

  DiscordRoleAssignFunction:
    Type: AWS::Serverless::Function
    Properties:
      #FunctionName: discord-role-assign
      CodeUri: ./src/role_assignment
      Description: "Serverless Function to set the role of a given user on Discord"
      Handler: index.lambdaHandler
      Environment:
        Variables:
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          DISCORD_CHANNEL_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:channel_id}}'
        
  DiscordPollResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
  #    FunctionName: discord-poll-results
      CodeUri: ./src/poll_results
      Description: "Serverless Function to count the results of a Discord poll and invoke the Enzyme Interaction API to execute the results."
      Handler: index.lambdaHandler
      Environment:
        Variables:
          DISCORD_BOT_TOKEN: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:bot_token}}'
          DISCORD_SERVER_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:server_id}}'
          DISCORD_CHANNEL_ID: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:channel_id}}'

Outputs:
  DiscordInteractionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${DiscordInteractionApi}.execute-api.${AWS::Region}.amazonaws.com/dev/event"
  DiscordRoleAssignFnArn:
    Description: "The ARN of the lambda function that assigns the roles on discord. Used to call that function after successful authentication."
    Value: !GetAtt DiscordRoleAssignFunction.Arn
    #Export:
    #  Name: DiscordRoleAssignFnArn
