AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  enzyme-interaction
  API to interact with Enzyme Finance Protocol

Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 10

Resources:
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./src/dependencies_layer

  EnzymeInteractionApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: dev

  GetVaultInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Description: "Get information about the vault"
      Handler: public.getVaultInfo
      Events:
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref EnzymeInteractionApi
            Method: get
            Path: /vault-info
      Environment:
        Variables:
          ETHEREUM_NODE_ENDPOINT: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:ethereum_node_endpoint}}'
      Layers:
        - !Ref DependenciesLayer

  ExecuteTradeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Description: "Get information about the vault"
      Handler: protected.executeTrade
      Environment:
        Variables:
          VAULT_ADDRESS: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:vault_address}}'
          ETHEREUM_NODE_ENDPOINT: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:ethereum_node_endpoint}}'
          VAULT_OWNER_ETH_PRIVATE_KEY: '{{resolve:secretsmanager:/dev/discord_dao_treasury_bot/discord:SecretString:vault_owner_eth_private_key}}'
      Layers:
        - !Ref DependenciesLayer
        
Outputs:
  EnzymeInteractionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${EnzymeInteractionApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Export:
      Name: EnzymeInteractionApi
  EnzymeExecuteTradeFunctionArn:
    Description: "The ARN of the Lambda function which executes trades on the Enzyme vault"
    Value: !GetAtt ExecuteTradeFunction.Arn
    Export:
      Name: EnzymeExecuteTradeFunctionArn
